doctors:
  host-name: localhost
  working-hours:
    startTime: 9
    endTime: 16
  specializations:
    - surgeon
    - therapist
    - oculist
    - psychologist
    - dentist

server:
  port: 8080

spring:
  h2:
    console:
      enabled: true