doctors:
  host-name: localhost
  working-hours:
    startTime: 9
    endTime: 16
  specializations:
    - surgeon
    - therapist
    - oculist
    - psychologist
    - dentist

server:
  port: 8080

spring:
  h2:
    console:
      enabled: true
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: create
      database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        temp:
          use_jdbc_metadata_defaults: false
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://192.168.0.107/doctors
    username: user
    password: test

#logging.level.org.hibernate.SQL: debug
#logging.level.org.hibernate.type.descriptor.sql: trace
