spring:
  datasource:
    driver-class-name: org.testcontainers.jdbc.ContainerDatabaseDriver
    url: jdbc:tc:postgresql://localhost/postgres
doctors:
  education-service:
    url: "http://localhost:8089"
